go:
    version: 1.14
    cgo: true
repository:
    path: github.com/brandond/homeplug_exporter
build:
    binaries: 
        - name: homeplug_exporter
    flags: -a -tags netgo
    static: true
    ldflags: |
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    files:
        - LICENSE
